# Generated by Django 5.0.1 on 2024-01-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
